#!/bin/sh
set -e
if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    if command -v systemctl >/dev/null 2>&1; then
        systemctl --global disable stek-plugin.service >/dev/null 2>&1 || true
    fi
fi
#DEBHELPER#
exit 0
